[versions]
hoplite = "2.9.0"
jib = "3.4.5"
hikaricp = "6.3.0"
kapper = "1.4.0"
koin-bom = "4.0.4"
kotlin = "2.1.10"
ktor = "3.1.2"
logback = "1.5.18"

[libraries]
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }

hoplite-core = { group = "com.sksamuel.hoplite", name = "hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { group = "com.sksamuel.hoplite", name = "hoplite-yaml", version.ref = "hoplite" }

kapper = { group = "net.samyn", name = "kapper", version.ref = "kapper" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
